### ISSUE TITLE
sbt-cpd pulls SNAPSHOT dependency for pmd-apex

### ISSUE THREAD

**Issue by ep-skolberg** [sbt/sbt-cpd#21]
### Expected vs Actual Behaviour

It should...
not cause using projects to pull SNAPSHOT dependencies

Instead it...
it causes using projects to pull apex-jorje-ide-1.0-sfdc-187-SNAPSHOT-55042bfc2e

### Steps to Reproduce

setup an sbt project and add

addSbtPlugin("com.github.sbt" %% "sbt-cpd" % "2.0.0")

try to start an sbt session
```
[info] Resolved  dependencies
[warn] 
[warn]  Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading apex:apex-jorje-semantic:1.0-sfdc-187-SNAPSHOT-55042bfc2e
...
```

### Environment

* sbt version: 1.5.4
* Plugin version: 2.0.0
* Scala version(s): 2.11.11 and 2.12.12 (include all versions if cross-building)_
* Java version: 1.8
* Link to project source: n.a.

**Comment by AngeloFilaseta** [comment]
Happened to me today while trying to configure a GitHub Action:
``` 
[info] welcome to sbt 1.5.5 (AdoptOpenJDK Java 1.8.0_292)
[info] loading settings for project pps-test-repository-build from plugins.sbt ...
[info] loading project definition from /home/runner/work/pps-test-repository/pps-test-repository/project
[warn] 
[warn] 	Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading apex:apex-jorje-semantic:1.0-sfdc-187-SNAPSHOT-55042bfc2e
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/apex/apex-jorje-semantic/1.0-sfdc-187-SNAPSHOT-55042bfc2e/apex-jorje-semantic-1.0-sfdc-187-SNAPSHOT-55042bfc2e.pom
[error]   not found: /home/runner/.ivy2/localapex/apex-jorje-semantic/1.0-sfdc-187-SNAPSHOT-55042bfc2e/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/apex/apex-jorje-semantic/1.0-sfdc-187-SNAPSHOT-55042bfc2e/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/apex/apex-jorje-semantic/1.0-sfdc-187-SNAPSHOT-55042bfc2e/ivys/ivy.xml
[error] Error downloading apex:apex-jorje-ide:1.0-sfdc-187-SNAPSHOT-55042bfc2e
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/apex/apex-jorje-ide/1.0-sfdc-187-SNAPSHOT-55042bfc2e/apex-jorje-ide-1.0-sfdc-187-SNAPSHOT-55042bfc2e.pom
[error]   not found: /home/runner/.ivy2/localapex/apex-jorje-ide/1.0-sfdc-187-SNAPSHOT-55042bfc2e/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/apex/apex-jorje-ide/1.0-sfdc-187-SNAPSHOT-55042bfc2e/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/apex/apex-jorje-ide/1.0-sfdc-187-SNAPSHOT-55042bfc2e/ivys/ivy.xml
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:258)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:227)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:227)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:59)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:133)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:146)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:146)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:127)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:160)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3678)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading apex:apex-jorje-semantic:1.0-sfdc-187-SNAPSHOT-55042bfc2e
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/apex/apex-jorje-semantic/1.0-sfdc-187-SNAPSHOT-55042bfc2e/apex-jorje-semantic-1.0-sfdc-187-SNAPSHOT-55042bfc2e.pom
[error]   not found: /home/runner/.ivy2/localapex/apex-jorje-semantic/1.0-sfdc-187-SNAPSHOT-55042bfc2e/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/apex/apex-jorje-semantic/1.0-sfdc-187-SNAPSHOT-55042bfc2e/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/apex/apex-jorje-semantic/1.0-sfdc-187-SNAPSHOT-55042bfc2e/ivys/ivy.xml
[error] Error downloading apex:apex-jorje-ide:1.0-sfdc-187-SNAPSHOT-55042bfc2e
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/apex/apex-jorje-ide/1.0-sfdc-187-SNAPSHOT-55042bfc2e/apex-jorje-ide-1.0-sfdc-187-SNAPSHOT-55042bfc2e.pom
[error]   not found: /home/runner/.ivy2/localapex/apex-jorje-ide/1.0-sfdc-187-SNAPSHOT-55042bfc2e/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/apex/apex-jorje-ide/1.0-sfdc-187-SNAPSHOT-55042bfc2e/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/apex/apex-jorje-ide/1.0-sfdc-187-SNAPSHOT-55042bfc2e/ivys/ivy.xml
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
Invalid response: 'ÿ'
```
This is what happens when any sbt command is called inside the ubuntu vm created if this plugin is enabled.

### Environment
sbt version: 1.5.5
Plugin version: 2.0.0
Scala version: 2.12.14
Java version: 1.8

**Comment by ccellado** [comment]
+1 got that error too
